In [1]:
import numpy as np

In [19]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [25]:
print(arr1[0])
print(arr1[1])
print(arr1[-1])
print(arr1[-4:-1])

1
2
5
[2 3 4]


# 2D- array

In [33]:
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [44]:
print(arr_2d[1,2])
print(arr_2d[0,4])
print(arr_2d[1,4])
 

8
5
10


In [47]:
arr_3d = np.array([[[1,2,3,4],[5,6,7,8]] , [[9,10,11,12],[13,14,15,16]]])
arr_3d
                   

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [51]:
print(arr_3d[0,1,1])
print(arr_3d[0,0,3]) #it will print 4 
print(arr_3d[1, 1, 3]) 

6
4
16


In [ ]:
The first number represents the first dimension, which contains two arrays:
[[1, 2, 3, 4], [4, 5, 6, 7]]
and:
[[8, 9,10, 11,12], [13,14,14,16]]
Since we selected 0, we are left with the first array:
[[1, 2, 3, 4], [4, 5, 6, 7]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3,4]
and:
[5, 6, 7, 8]
Since we selected 1, we are left with the second array:
[4, 5, 6, 7]

The third number represents the third dimension, which contains three values:
4
5
6
7
Since we selected 2, we end up with the third value:
6

# slicing


In [58]:
slic = np. array([0,1,2,3,4,5,6,7,8,9])
print(slic)

print(slic[0:6])
print(slic[-5:-1])
print(slic[:4])
print(slic[::-1])
print(slic[0:8:2])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5]
[5 6 7 8]
[0 1 2 3]
[9 8 7 6 5 4 3 2 1 0]
[0 2 4 6]


#  Slicing 2-D Arrays

In [66]:
sli_2d = np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(sli_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [67]:

print(sli_2d[0, 1:])

[1 2 3 4]


In [72]:
print(sli_2d[0, 0:2])
print(sli_2d[1, 0:3])
print(sli_2d[1, 1:3])

[0 1]
[5 6 7]
[6 7]


# Data Types in Python

By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
integer - used to represent integer numbers. e.g. -1, -2, -3
float - used to represent real numbers. e.g. 1.2, 42.42
boolean - used to represent True or False.
complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

Creating Arrays With a Defined Data Type
We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:



In [73]:
 
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [74]:
# Create an array with data type 4 bytes integer:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
# The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.



In [ ]:

print(sli_2d[0, 1:])

In [27]:
arr=np.array([1,2,3])

In [7]:
arr


array([1, 2, 3])

In [26]:
a=np.array([1,2,3],ndmin= 5)
a

array([[[[[1, 2, 3]]]]])

In [10]:
new_array=np.array([1,5,3,4])
new_array

array([1, 5, 3, 4])

In [11]:
new_array.shape

(4,)

In [28]:
new_array1=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,5]])

In [29]:
new_array1

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 5]])

In [30]:
new_array1.shape

(3, 4)

In [31]:
new_array1.size

12

In [32]:
new_array1.ndim()

TypeError: 'int' object is not callable

In [34]:
#get/set elements
new_array1[1,3]


4

In [35]:
new_array1[1,3]=-1

In [37]:
new_array1

array([[ 1,  2,  3,  4],
       [ 1,  2,  3, -1],
       [ 1,  2,  3,  5]])

In [47]:
new_array1[2,3]=8

In [48]:
new_array1

array([[     1,      2,      3,      4],
       [     1,      2,      3, 818487],
       [     1,      2,      3,      8]])

In [63]:
new_array1[0]=25

In [64]:
new_array1

array([[    25,     25,     25,     25],
       [     1,    123,      3, 818487],
       [     1,      2,      3,      8]])

In [65]:
# fill , it fills all elements with same value
new_array1.fill(1)

In [66]:
new_array1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [67]:
new_array1[0:2]=5

In [68]:
new_array1

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [1, 1, 1, 1]])

In [69]:
new_array1[:]

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [1, 1, 1, 1]])

In [72]:
new_array1[:]=10.5

In [73]:
new_array1

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [49]:
new_array1[1,1]=123

In [50]:
new_array1

array([[     1,      2,      3,      4],
       [     1,    123,      3, 818487],
       [     1,      2,      3,      8]])

In [54]:
#to check datatype
new_array1.dtype


dtype('int32')

In [55]:
#to find size of array
new_array1.itemsize

4

In [57]:
# to find the total bytes size of array
new_array1.nbytes



48

In [58]:
#conversion to list
new_array1.tolist()

[[1, 2, 3, 4], [1, 123, 3, 818487], [1, 2, 3, 8]]

In [61]:
# to copy array to another variable
a=new_array1.copy()

In [62]:
a

array([[     1,      2,      3,      4],
       [     1,    123,      3, 818487],
       [     1,      2,      3,      8]])

In [40]:
#adderss first fow using single index
new_array1[0]


array([1, 2, 3, 4])

In [12]:
new_array=np.array([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]])

In [13]:
new_array

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [14]:
new_array.shape

(3, 3, 3)

In [18]:
# to check dimenction of array

new_array.ndim


3

In [74]:
# slicing

In [90]:
a=np.array((0,1,2,3,4,5))

In [91]:
a

array([0, 1, 2, 3, 4, 5])

In [92]:
b=a[2:4]

In [93]:
a

array([0, 1, 2, 3, 4, 5])

In [94]:
b

array([2, 3])

# indexing

In [98]:
a=np.arange(0,100,10)

In [99]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [100]:
x=a[[1,2,-4]]

In [101]:
x

array([10, 20, 60])

In [104]:
y=np.take(a,[0,1,2,3])

In [105]:
y

array([ 0, 10, 20, 30])

# Reshape


In [32]:
# Reshaping means changing the shape of an array.

# The shape of an array is the number of elements in each dimension.

# By reshaping we can add or remove dimensions or change number of elements in each dimension.


re_arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(re_arr.reshape(3,2,2))
print(type(re_arr.ndim))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
<class 'int'>


In [24]:
_arr=re_arr.reshape(4,3,-1)
print(_arr)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [29]:
print(_arr.ndim)

3


# Iterating Arrays
Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [34]:
ite_arr = np.array([1,2,3,4,5])
for lis in ite_arr:
    print(lis, end =" ")

1 2 3 4 5 

# Iterating 2-D Arrays
In a 2-D array it will go through all the rows.

In [37]:
ite_2d_arr = np.array([[1,2,3,4,],[5,6,7,8]])

print(ite_2d_arr.ndim)

for lis in ite_2d_arr:
    print(lis)

2
[1 2 3 4]
[5 6 7 8]


In [ ]:
# If we iterate on a n-D array it will go through n-1th dimension one by one.